apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: srpx43pjf-go 
  janus-idp.io/tekton: srpx43pjf-go
  backstage.io/kubernetes-id: srpx43pjf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: srpx43pjf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  