apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: srpx43pjf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: srpx43pjf-go 
  name: srpx43pjf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: srpx43pjf-go 
